In [106]:
import pandas as pd
from pathlib import Path
import json
import requests
import io

In [107]:
# url="https://raw.githubusercontent.com/GoogleTrends/data/gh-pages/20170816_Documenting_Hate.csv"
# s=requests.get(url).content
# c=pd.read_csv(io.StringIO(s.decode('ansi')))

In [273]:
# setting paths to input files directory & output files directory
input_files_path = Path("../input_files")
output_file_path = Path("../output_files")

#selecting hate-crime file to read from input file directory
input_file1 = "hate_crime.csv"
file_to_open = input_files_path / input_file1

# reading input file to a DataFrame
df = pd.read_csv(file_to_open, low_memory = False)
df.head(5)

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
0,3015,1991,AR0040200,Rogers,NaN,City,AR,Arkansas,West South Central,South,...,White,NaN,1,Intimidation,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American,Individual,S,S
1,3016,1991,AR0290100,Hope,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Simple Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,S,S
2,43,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
3,44,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,S
4,3017,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Service/Gas Station,Anti-White,Individual,S,S

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194194 entries, 0 to 194193
Data columns (total 28 columns):
INCIDENT_ID                 194194 non-null int64
DATA_YEAR                   194194 non-null int64
ORI                         194194 non-null object
PUB_AGENCY_NAME             194194 non-null object
PUB_AGENCY_UNIT             5219 non-null object
AGENCY_TYPE_NAME            194194 non-null object
STATE_ABBR                  194194 non-null object
STATE_NAME                  194194 non-null object
DIVISION_NAME               194194 non-null object
REGION_NAME                 194194 non-null object
POPULATION_GROUP_CODE       194194 non-null object
POPULATION_GROUP_DESC       194194 non-null object
INCIDENT_DATE               194194 non-null object
ADULT_VICTIM_COUNT          29915 non-null float64
JUVENILE_VICTIM_COUNT       29813 non-null float64
TOTAL_OFFENDER_COUNT        194194 non-null int64
ADULT_OFFENDER_COUNT        28704 non-null float64
JUVENILE_OFFENDER_COUNT     28702 non-null float64
OFFENDER_RACE               194189 non-null object
OFFENDER_ETHNICITY          11827 non-null object
VICTIM_COUNT                194194 non-null int64
OFFENSE_NAME                194194 non-null object
TOTAL_INDIVIDUAL_VICTIMS    193297 non-null float64
LOCATION_NAME               194194 non-null object
BIAS_DESC                   194194 non-null object
VICTIM_TYPES                194194 non-null object
MULTIPLE_OFFENSE            194194 non-null object
MULTIPLE_BIAS               194194 non-null object
dtypes: float64(5), int64(4), object(19)
memory usage: 41.5+ MB

In [137]:
# deleting data before 2007
df = df.loc[df['DATA_YEAR']>=2007, :]

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 72894 entries, 121300 to 194193
Data columns (total 28 columns):
INCIDENT_ID                 72894 non-null int64
DATA_YEAR                   72894 non-null int64
ORI                         72894 non-null object
PUB_AGENCY_NAME             72894 non-null object
PUB_AGENCY_UNIT             1897 non-null object
AGENCY_TYPE_NAME            72894 non-null object
STATE_ABBR                  72894 non-null object
STATE_NAME                  72894 non-null object
DIVISION_NAME               72894 non-null object
REGION_NAME                 72894 non-null object
POPULATION_GROUP_CODE       72894 non-null object
POPULATION_GROUP_DESC       72894 non-null object
INCIDENT_DATE               72894 non-null object
ADULT_VICTIM_COUNT          29915 non-null float64
JUVENILE_VICTIM_COUNT       29813 non-null float64
TOTAL_OFFENDER_COUNT        72894 non-null int64
ADULT_OFFENDER_COUNT        28704 non-null float64
JUVENILE_OFFENDER_COUNT     28702 non-null float64
OFFENDER_RACE               72889 non-null object
OFFENDER_ETHNICITY          11827 non-null object
VICTIM_COUNT                72894 non-null int64
OFFENSE_NAME                72894 non-null object
TOTAL_INDIVIDUAL_VICTIMS    71997 non-null float64
LOCATION_NAME               72894 non-null object
BIAS_DESC                   72894 non-null object
VICTIM_TYPES                72894 non-null object
MULTIPLE_OFFENSE            72894 non-null object
MULTIPLE_BIAS               72894 non-null object
dtypes: float64(5), int64(4), object(19)
memory usage: 16.1+ MB

## Dropping non- useful columns

'INCIDENT_ID' ( a number assigned to every crime record- not useful for our analysis)

'PUB_AGENCY_UNIT' (only populated in approx 2% records, not useful for our analysis)

'POPULATION_GROUP_CODE' (just a alphanumeric code assigned for categorical data in POPULATION_GROUP, another column)

'OFFENDER_ETHNICITY' (available for approx 15% records, not useful for our analysis)

In [138]:
df.drop(['INCIDENT_ID', 'PUB_AGENCY_UNIT', 'POPULATION_GROUP_CODE','OFFENDER_ETHNICITY'], axis = 1, inplace = True)

# dropping 'STATE_NAME' (we already have a duplicate column as STATE_ABBR, will save a dictionary, in case we meed to map to full name)
state_name_dict = dict(zip(df['STATE_ABBR'].tolist(), df['STATE_NAME'].tolist()))
df.drop('STATE_NAME', axis = 1, inplace = True)

### converting INCIDENT_DATE from string to date-time dtype, as might be needed for seasonal analysis
### also retaining only month under this column, year is already in 'DATA_YEAR' column

In [139]:
df['INCIDENT_DATE'] = pd.to_datetime(df['INCIDENT_DATE'])
df['INCIDENT_DATE'] = pd.DatetimeIndex(df['INCIDENT_DATE']).month
df['INCIDENT_DATE'].unique()

array([ 3,  4,  5,  6,  8,  9, 10, 12, 11,  7,  2,  1], dtype=int64)

In [89]:
df.head()

,DATA_YEAR,ORI,PUB_AGENCY_NAME,AGENCY_TYPE_NAME,STATE_ABBR,DIVISION_NAME,REGION_NAME,POPULATION_GROUP_DESC,INCIDENT_DATE,ADULT_VICTIM_COUNT,...,JUVENILE_OFFENDER_COUNT,OFFENDER_RACE,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
121300,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",3,NaN,...,NaN,American Indian or Alaska Native,1,Simple Assault,2.0,Other/Unknown,Anti-Mental Disability,Individual,S,S
121301,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",3,NaN,...,NaN,Unknown,1,Destruction/Damage/Vandalism of Property,1.0,Parking/Drop Lot/Garage,Anti-Black or African American,Individual,S,S
121302,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",3,NaN,...,NaN,White,1,Aggravated Assault,1.0,Parking/Drop Lot/Garage,Anti-Gay (Male),Individual,S,S
121303,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",4,NaN,...,NaN,American Indian or Alaska Native,1,Simple Assault,2.0,Hotel/Motel/Etc.,Anti-Gay (Male),Individual,S,S
121304,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",5,NaN,...,NaN,Unknown,1,Destruction/Damage/Vandalism of Property,1.0,Residence/Home,Anti-Black or African American,Individual,S,S

### (1) May keep either 'DIVISION_NAME', or 'REGION_NAME' (presently retaining both)

'DIVISION_NAME' -     ['Pacific', 'East South Central', 'West South Central', 'Mountain',
       'New England', 'South Atlantic', 'West North Central',
       'East North Central', 'Middle Atlantic', 'U.S. Territories']
    
'REGION_NAME' -['West', 'South', 'Northeast', 'Midwest', 'U.S. Territories']


### (2)  'ORI' is an ID assigned to 'PUB_AGENCY_NAME' hence we can keep only one of them.

In [90]:
df.columns

Index(['DATA_YEAR', 'ORI', 'PUB_AGENCY_NAME', 'AGENCY_TYPE_NAME', 'STATE_ABBR',
       'DIVISION_NAME', 'REGION_NAME', 'POPULATION_GROUP_DESC',
       'INCIDENT_DATE', 'ADULT_VICTIM_COUNT', 'JUVENILE_VICTIM_COUNT',
       'TOTAL_OFFENDER_COUNT', 'ADULT_OFFENDER_COUNT',
       'JUVENILE_OFFENDER_COUNT', 'OFFENDER_RACE', 'VICTIM_COUNT',
       'OFFENSE_NAME', 'TOTAL_INDIVIDUAL_VICTIMS', 'LOCATION_NAME',
       'BIAS_DESC', 'VICTIM_TYPES', 'MULTIPLE_OFFENSE', 'MULTIPLE_BIAS'],
      dtype='object')

In [91]:
df.head()

,DATA_YEAR,ORI,PUB_AGENCY_NAME,AGENCY_TYPE_NAME,STATE_ABBR,DIVISION_NAME,REGION_NAME,POPULATION_GROUP_DESC,INCIDENT_DATE,ADULT_VICTIM_COUNT,...,JUVENILE_OFFENDER_COUNT,OFFENDER_RACE,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
121300,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",3,NaN,...,NaN,American Indian or Alaska Native,1,Simple Assault,2.0,Other/Unknown,Anti-Mental Disability,Individual,S,S
121301,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",3,NaN,...,NaN,Unknown,1,Destruction/Damage/Vandalism of Property,1.0,Parking/Drop Lot/Garage,Anti-Black or African American,Individual,S,S
121302,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",3,NaN,...,NaN,White,1,Aggravated Assault,1.0,Parking/Drop Lot/Garage,Anti-Gay (Male),Individual,S,S
121303,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",4,NaN,...,NaN,American Indian or Alaska Native,1,Simple Assault,2.0,Hotel/Motel/Etc.,Anti-Gay (Male),Individual,S,S
121304,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",5,NaN,...,NaN,Unknown,1,Destruction/Damage/Vandalism of Property,1.0,Residence/Home,Anti-Black or African American,Individual,S,S

In [129]:
# 'BIAS_DESC' contains multiple biases(upto 3) separated by ';', hence separating into 3 separate columns
# first creating a temporaty dataframe by splitting the 'BIAS_DESC' column
df_temp= df["BIAS_DESC"].str.split(";", n = 2, expand = True) 
  

# assigning split columns to our main dataframe
# we can delete column 'BIAS_DESC' now (presently retaining it)
df['BIAS_1'] = df_temp[0] 
df['BIAS_2'] = df_temp[1] 
df['BIAS_3'] = df_temp[2] 
df.head()

,DATA_YEAR,ORI,PUB_AGENCY_NAME,AGENCY_TYPE_NAME,STATE_ABBR,DIVISION_NAME,REGION_NAME,POPULATION_GROUP_DESC,INCIDENT_DATE,ADULT_VICTIM_COUNT,...,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS,BIAS_1,BIAS_2,BIAS_3
121300,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",3,NaN,...,Simple Assault,2.0,Other/Unknown,Anti-Mental Disability,Individual,S,S,Anti-Mental Disability,None,None
121301,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",3,NaN,...,Destruction/Damage/Vandalism of Property,1.0,Parking/Drop Lot/Garage,Anti-Black or African American,Individual,S,S,Anti-Black or African American,None,None
121302,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",3,NaN,...,Aggravated Assault,1.0,Parking/Drop Lot/Garage,Anti-Gay (Male),Individual,S,S,Anti-Gay (Male),None,None
121303,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",4,NaN,...,Simple Assault,2.0,Hotel/Motel/Etc.,Anti-Gay (Male),Individual,S,S,Anti-Gay (Male),None,None
121304,2007,AK0010100,Anchorage,City,AK,Pacific,West,"Cities from 250,000 thru 499,999",5,NaN,...,Destruction/Damage/Vandalism of Property,1.0,Residence/Home,Anti-Black or African American,Individual,S,S,Anti-Black or African American,None,None

In [132]:
# check the bias categories in 'BIAS_3' column
#df_temp.BIAS3.unique()



#We can reorder the columns with below command (any sequence)
'''
df = df[['DATA_YEAR', 'ORI', 'PUB_AGENCY_NAME', 'AGENCY_TYPE_NAME', 'STATE_ABBR',
       'DIVISION_NAME', 'REGION_NAME', 'POPULATION_GROUP_DESC',
       'INCIDENT_DATE', 'ADULT_VICTIM_COUNT', 'JUVENILE_VICTIM_COUNT',
       'TOTAL_OFFENDER_COUNT', 'ADULT_OFFENDER_COUNT',
       'JUVENILE_OFFENDER_COUNT', 'OFFENDER_RACE', 'VICTIM_COUNT',
       'OFFENSE_NAME', 'TOTAL_INDIVIDUAL_VICTIMS', 'LOCATION_NAME',
       'BIAS_DESC', 'VICTIM_TYPES', 'MULTIPLE_OFFENSE', 'MULTIPLE_BIAS',
       'BIAS_1', 'BIAS_2', 'BIAS_3']]
'''
df.columns

Index(['DATA_YEAR', 'ORI', 'PUB_AGENCY_NAME', 'AGENCY_TYPE_NAME', 'STATE_ABBR',
       'DIVISION_NAME', 'REGION_NAME', 'POPULATION_GROUP_DESC',
       'INCIDENT_DATE', 'ADULT_VICTIM_COUNT', 'JUVENILE_VICTIM_COUNT',
       'TOTAL_OFFENDER_COUNT', 'ADULT_OFFENDER_COUNT',
       'JUVENILE_OFFENDER_COUNT', 'OFFENDER_RACE', 'VICTIM_COUNT',
       'OFFENSE_NAME', 'TOTAL_INDIVIDUAL_VICTIMS', 'LOCATION_NAME',
       'BIAS_DESC', 'VICTIM_TYPES', 'MULTIPLE_OFFENSE', 'MULTIPLE_BIAS',
       'BIAS_1', 'BIAS_2', 'BIAS_3'],
      dtype='object')


  ## *<font color=red>Our Main Data Frame 'df' is now ready for use*</font>

# importing data from FBI Crime website using API's

In [141]:
# importing api_key as saved in config.py file in same folder (Please type in your fbi api key in config.py file )
from config import api_key

## Query_URL :  base_url  + endpoint +? + apl_key=".."

### base_url = "https://api.usa.gov/crime/fbi/sapi/"

### Many endpoints are offered by FBI but no endpoint offered for hate crimes category. 

### we have used below endpoint to consolidate crime data by agencies (ORI) and OFFENSE_NAME as also appearing in our main dataframe. We can use it to compare trends in hate-crime vs. overall crime 
#### /api/summarized/agencies/{ori}/offenses/2007/2017

In [258]:
base_url = "https://api.usa.gov/crime/fbi/sapi"

# making one sample call to check teh json response structure
endpoint = f'/api/summarized/agencies/CA0010400/offenses/2007/2017'
response = requests.get(f"{base_url}{endpoint}?api_key={api_key}").json()
response.keys()

dict_keys(['results', 'pagination'])

In [259]:
# checking a sample record under 'results'
response['results'][0]

{'ori': 'CA0010400',
 'data_year': 2007,
 'offense': 'aggravated-assault',
 'state_abbr': 'CA',
 'cleared': 17,
 'actual': 25}

In [268]:
# making a list of all agencies as appearing in our hate-crime daraframe
ori_list = df.ORI.unique().tolist()

# making a dictionary structure to collat the data colected in each API call.
dict ={'ORI':[], 'DATA_YEAR':[], 'OFFENSE_NAME':[], 'STATE_ABBR':[], 'CLEARED':[], 'ACTUAL':[]}

# we will make one API call for each of 6300+ agencies in hate-crime database


for ori in ori_list:
         
    endpoint = f'/api/summarized/agencies/{ori}/offenses/2007/2017'
    response = requests.get(f"{base_url}{endpoint}?api_key={api_key}").json()
    
    for i in range(len(h['results'])):
        dict['ORI'].append(h['results'][i]['ori'])
        dict['DATA_YEAR'].append(h['results'][i]['data_year'])
        dict['OFFENSE_NAME'].append(h['results'][i]['offense'])
        dict['STATE_ABBR'].append(h['results'][i]['state_abbr'])
        dict['CLEARED'].append(h['results'][i]['cleared'])
        dict['ACTUAL'].append(h['results'][i]['actual'])
     
            
df2 = pd.DataFrame(dict)

df2.head()

         ORI  DATA_YEAR        OFFENSE_NAME STATE_ABBR  CLEARED  ACTUAL
0  CA0010700       2007  aggravated-assault         CA       36      83
1  CA0010700       2007               arson         CA        5      31
2  CA0010700       2007            burglary         CA       43     385
3  CA0010700       2007            homicide         CA        0       1
4  CA0010700       2007    human-trafficing         CA        0       0

In [269]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 841632 entries, 0 to 841631
Data columns (total 6 columns):
ORI             841632 non-null object
DATA_YEAR       841632 non-null int64
OFFENSE_NAME    841632 non-null object
STATE_ABBR      841632 non-null object
CLEARED         841632 non-null int64
ACTUAL          841632 non-null int64
dtypes: int64(3), object(3)
memory usage: 38.5+ MB

In [274]:
# saving API call data in a csv file

output_file1 = "crime_data_2007-2017.csv"
file_to_write = output_file_path / output_file1
df2.to_csv(file_to_write, encoding='utf-8')

  ## *<font color=red>Our Data Frame 'df2' is now ready to look for consolidated crime data agencywise/citywise*</font>